version: '3'
services:
  backend:
    build: ./flask-boilerplate
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./flask-boilerplate:/app

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
